# Enable native Wayland for sharp HiDPI scaling on Hyprland
--ozone-platform-hint=auto

# Hardware Video Acceleration & Tab Energy Saver
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy

# Wayland text input / virtual keyboard support
--enable-wayland-ime

# Native Touchscreen Experience: History Overscroll, Pull-to-Refresh & Smooth Inertial Scrolling
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,TouchpadOverscrollHistoryNavigation,PullToRefresh,HighEfficiencyModeAvailable,BatterySaverModeAvailable
--touch-events=enabled
--enable-touch-drag-drop
--smooth-scrolling
