# Enable native Wayland for sharp HiDPI scaling on Hyprland
--ozone-platform-hint=auto

# Smooth touchscreen & touchpad gestures + VA-API Hardware Video Decoding + Tab Energy Saver
--enable-features=VaapiVideoDecodeLinuxGL,VaapiVideoDecoder,TouchpadOverscrollHistoryNavigation,HighEfficiencyModeAvailable,BatterySaverModeAvailable
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy

# Wayland text input / virtual keyboard support
--enable-wayland-ime
